site:
  url: "https://trgoalsgiris.xyz/"
  timeout: 10
  user_agent: "Mozilla/5.0"

output:
  file: "https://trgoals.m3u"
  logo: "https://i.hizliresim.com/ska5t9e.jpg"
  group: "SPORTS"

update_interval_minutes: 15
