name: Auto M3U Generator

on:
  schedule:
    - cron: "0 */6 * * *"   # h…ôr 6 saatda bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python build.py

      - name: Commit & Push updated M3U
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add DeaTHLesS-sports.m3u
          git commit -m "Auto update M3U"
          git push
